matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
    - os: osx

language: go
go:
  - "1.10"

addons:
  apt:
    packages:
      - gfortran

install:
  - go generate
  - export CGO_LDFLAGS_ALLOW="-Wl*"

script:
  - go build
  - ls lib
  - MKL_CBWR=SSE4_1 go test
