matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
    - os: osx

language: go
go:
  - "1.10"

addons:
  apt:
    packages:
      - gfortran

install:
  - make
  - export CGO_LDFLAGS_ALLOW="-Wl*"

script:
  - go test
